"""Render the runtime's dora dataflow YAML (14-dora §2.3).

The text is rendered by hand (not ``yaml.dump``) so the file is byte-stable,
commented and diffable; ``dataflows/mavis_v2.example.dora.yml`` in the repo is
the rendered result for the sim config and ``tests/dora/test_dataflow.py``
pins the renderer to it and runs ``dora validate --strict-types`` over it.

Rules baked in: every runtime input is ``queue_size: 1, drop_oldest`` except
``policy_spec`` (1, keep), ``policy_status`` (8) and ``policy_trainer_status`` (8,
phase-14); ``events`` fan-out is 64;
``input_timeout`` is never set; ``debug.enable_debug_inspection`` is never
emitted (coordinator bug, §8); the interpreter of the one spawned node is
pinned; every node carries ``deploy: {machine: <id>}``; remote placeholders
are rendered ONLY for machines whose daemon is registered (``dora start``
refuses a dataflow naming an absent machine).
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence

from apollo_mavis_v2_core.protocol import external as ext

from ..config import DoraConfig

HEADER = "# generated by apollo_mavis_v2_runtime.dora_bridge.dataflow - do not edit"

# -- fixed shapes -----------------------------------------------------------------------------
CANARY_NODE_ID = "canary"  # runtime-internal dynamic node (not a foreign placeholder)
_Q1_DROP = "{source: %s, queue_size: 1, queue_policy: drop_oldest}"


def runtime_outputs(
    camera_ids: Sequence[str], depth_camera_ids: Sequence[str], mic_id: str | None
) -> list[str]:
    """Every output id ``mavis_runtime`` declares, in the fixed order of 14-dora §4.1."""
    out = list(ext.RUNTIME_FIXED_OUTPUTS)
    for cam in camera_ids:
        out.append(ext.camera_output_id(cam))
        if cam in depth_camera_ids:
            out.append(ext.depth_output_id(cam))
    if mic_id:
        out.append(ext.mic_output_id(mic_id))
    return out


def _runtime_inputs() -> list[str]:
    return [
        f"{ext.IN_TICK}: {ext.TICK_TIMER}",
        f"{ext.IN_PROBE_HEARTBEAT}: {ext.PROBE_NODE_ID}/{ext.PROBE_OUT_HEARTBEAT}",
        f"{ext.IN_POLICY_ACTION}: "
        + _Q1_DROP % f"{ext.PLACEHOLDER_POLICY}/{ext.POLICY_OUT_ACTION}",
        f"{ext.IN_POLICY_SPEC}: {{source: {ext.PLACEHOLDER_POLICY}/{ext.POLICY_OUT_SPEC}, "
        "queue_size: 1}",
        f"{ext.IN_POLICY_STATUS}: {{source: {ext.PLACEHOLDER_POLICY}/{ext.POLICY_OUT_STATUS}, "
        "queue_size: 8}",
        # phase-14 (15-online-dagger §6): the trainer role's JSON status, 1 Hz + on change
        f"{ext.IN_POLICY_TRAINER_STATUS}: {{source: {ext.PLACEHOLDER_POLICY}/"
        f"{ext.POLICY_OUT_TRAINER_STATUS}, queue_size: 8}}",
    ]


def _policy_inputs(camera_ids: Sequence[str]) -> list[str]:
    rt = ext.EXTERNAL_NODE_ID
    rows = [
        f"{ext.OUT_OBS_STATE}: " + _Q1_DROP % f"{rt}/{ext.OUT_OBS_STATE}",
        f"{ext.OUT_SESSION}: {rt}/{ext.OUT_SESSION}",
        f"{ext.OUT_POLICY_RESET}: {rt}/{ext.OUT_POLICY_RESET}",
        f"{ext.OUT_EVENTS}: {{source: {rt}/{ext.OUT_EVENTS}, queue_size: 64}}",
    ]
    for cam in camera_ids:
        cid = ext.camera_output_id(cam)
        rows.append(f"{cid}: " + _Q1_DROP % f"{rt}/{cid}")
    return rows


def _viewer_inputs(camera_ids: Sequence[str], depth_camera_ids: Sequence[str]) -> list[str]:
    rt = ext.EXTERNAL_NODE_ID
    rows = [
        f"{ext.OUT_ARM_STATE}: " + _Q1_DROP % f"{rt}/{ext.OUT_ARM_STATE}",
        f"{ext.OUT_SESSION}: {rt}/{ext.OUT_SESSION}",
    ]
    for cam in camera_ids:
        cid = ext.camera_output_id(cam)
        rows.append(f"{cid}: " + _Q1_DROP % f"{rt}/{cid}")
        if cam in depth_camera_ids:
            did = ext.depth_output_id(cam)
            rows.append(f"{did}: " + _Q1_DROP % f"{rt}/{did}")
    return rows


_LOSSLESS_LOW_RATE = (ext.OUT_SESSION, ext.OUT_TELEMETRY, ext.OUT_POLICY_RESET, ext.OUT_HEARTBEAT)


def _observer_inputs(outputs: Sequence[str]) -> list[str]:
    """An observer is a logger: the high-rate image / state streams are latest-wins
    (``queue_size: 1``), but the streams a log must not lose get a queue that rides out a
    consumer hiccup - ``mic_*`` 32 blocks (1.3 s at 25 Hz; with ``queue_size: 1`` a single
    40 ms stall in 60 s cost one block, measured 2026-09-08), ``events`` 64, the low-rate
    ``session`` / ``telemetry`` / ``policy_reset`` / ``heartbeat`` 8."""
    rt = ext.EXTERNAL_NODE_ID
    rows = []
    for oid in outputs:
        if oid == ext.OUT_EVENTS:
            rows.append(f"{oid}: {{source: {rt}/{oid}, queue_size: 64}}")
        elif oid.startswith(ext.MIC_OUTPUT_PREFIX):
            rows.append(f"{oid}: {{source: {rt}/{oid}, queue_size: 32}}")
        elif oid in _LOSSLESS_LOW_RATE:
            rows.append(f"{oid}: {{source: {rt}/{oid}, queue_size: 8}}")
        else:
            rows.append(f"{oid}: " + _Q1_DROP % f"{rt}/{oid}")
    return rows


def _node(lines: list[str], node_id: str, machine: str, comment: str = "") -> None:
    lines.append(f"  - id: {node_id}" + (f"  # {comment}" if comment else ""))
    lines.append(f"    deploy: {{machine: {machine}}}")


def _inputs(lines: list[str], rows: Sequence[str]) -> None:
    lines.append("    inputs:")
    for row in rows:
        lines.append(f"      {row}")


def _outputs(lines: list[str], ids: Sequence[str]) -> None:
    lines.append("    outputs: [" + ", ".join(ids) + "]")


def render_dataflow(
    cfg: DoraConfig,
    camera_ids: Sequence[str],
    mic_id: str | None,
    python: str,
    registered_machines: Sequence[str] = (),
    *,
    depth_camera_ids: Sequence[str] | None = None,
) -> str:
    """The dataflow text for this config. ``camera_ids`` are the camera ids the runtime
    will actually publish (already filtered by ``cfg.publish.cameras``);
    ``depth_camera_ids`` default to ``cfg.publish.depth_cameras`` intersected with them;
    ``mic_id`` ``None`` = no microphone output; ``python`` is the interpreter that runs
    the probe node (``sys.executable`` of the runtime venv); ``registered_machines``
    are the ``cfg.machines`` ids whose daemons are registered right now."""
    cams = list(camera_ids)
    depth = [
        c
        for c in (depth_camera_ids if depth_camera_ids is not None else cfg.publish.depth_cameras)
        if c in cams
    ]
    outs = runtime_outputs(cams, depth, mic_id if cfg.publish.audio else None)
    me = cfg.machine_id
    lines = [
        HEADER,
        f"# dataflow {cfg.dataflow_name}; local machine {me}; mavis_schema {ext.MAVIS_SCHEMA}",
        "nodes:",
    ]

    _node(lines, cfg.node_id, me, "the runtime attaches here (Node(node_id)); never spawned")
    lines.append("    path: dynamic")
    _inputs(lines, _runtime_inputs())
    _outputs(lines, outs)

    _node(
        lines, ext.PLACEHOLDER_POLICY, me, 'placeholder: the policy repo attaches as Node("policy")'
    )
    lines.append("    path: dynamic")
    _inputs(lines, _policy_inputs(cams))
    _outputs(lines, list(ext.POLICY_OUTPUTS))

    _node(
        lines,
        ext.PLACEHOLDER_VIEWER,
        me,
        "placeholder: fixed-viewpoint consumer; inputs only, no outputs",
    )
    lines.append("    path: dynamic")
    _inputs(lines, _viewer_inputs(cams, depth))

    _node(lines, ext.PLACEHOLDER_OBSERVER, me, "placeholder: loggers / rerun bridges")
    lines.append("    path: dynamic")
    _inputs(lines, _observer_inputs(outs))

    configured = {m.id: list(m.placeholders) for m in cfg.machines}
    for mid in registered_machines:
        kinds = configured.get(mid)
        if not kinds:
            continue
        for kind in kinds:
            nid = ext.remote_placeholder_id(kind, mid)
            _node(lines, nid, mid, f"remote placeholder on machine {mid} (14-dora §9)")
            lines.append("    path: dynamic")
            if kind == ext.PLACEHOLDER_VIEWER:
                _inputs(lines, _viewer_inputs(cams, depth))
            else:
                _inputs(lines, _observer_inputs(outs))

    _node(
        lines,
        CANARY_NODE_ID,
        me,
        "lab-side start-barrier canary: the bridge attaches it in a SUBPROCESS after a "
        "restart with remote placeholders and only attaches mavis_runtime once it returned "
        "(a blocked Node() holds the GIL; 14-dora §16.1)",
    )
    lines.append("    path: dynamic")
    _inputs(
        lines,
        [
            f"{ext.PROBE_OUT_HEARTBEAT}: "
            + _Q1_DROP % f"{ext.PROBE_NODE_ID}/{ext.PROBE_OUT_HEARTBEAT}"
        ],
    )
    _node(
        lines,
        ext.PROBE_NODE_ID,
        me,
        "the ONLY spawned node: keeps the dataflow Running + liveness canary",
    )
    lines.append(f"    path: {python}")
    lines.append("    args: -m apollo_mavis_v2_runtime.dora_bridge.nodes.probe")
    lines.append("    env: {RUST_LOG: error}")
    _inputs(lines, [f"{ext.IN_TICK}: {ext.PROBE_TIMER}"])
    _outputs(lines, [ext.PROBE_OUT_HEARTBEAT])
    return "\n".join(lines) + "\n"


def placeholders_for(
    cfg: DoraConfig, registered_machines: Sequence[str]
) -> Mapping[str, list[str]]:
    """``{machine_id: [node ids rendered for it]}`` for the registered machines."""
    configured = {m.id: list(m.placeholders) for m in cfg.machines}
    out: dict[str, list[str]] = {}
    for mid in registered_machines:
        kinds = configured.get(mid)
        if kinds:
            out[mid] = [ext.remote_placeholder_id(k, mid) for k in kinds]
    return out


__all__ = ["CANARY_NODE_ID", "HEADER", "placeholders_for", "render_dataflow", "runtime_outputs"]
